[package]
name = "payload_dumper"
version = "0.7.0"
edition = "2024"
authors = ["rhythmcache"]
description = "Rust-based CLI utility to extract Android OTA payload.bin"
repository = "https://github.com/rhythmcache/payload-dumper-rust"
readme = "README.md"
license = "Apache-2.0"
homepage = "https://github.com/rhythmcache/payload-dumper-rust"
keywords = ["dumper", "android", "ota", "extractor", "payload"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.99"
byteorder = "1.5.0"
digest = "0.10.7"
indicatif = "0.18.0"
prost = "0.14.1"
sha2 = "0.10.9"
rayon = "1.10.0"
memmap2 = "0.9.7"
brotli = "8.0.1"
zstd = "0.13.3"
num_cpus = "1.17.0"
rand = "0.9.2"
hex = "0.4.3"
bzip2 = { version = "0.6", features = ["bzip2-sys", "static"] }
clap = { version = "4.5.45", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"], optional = true }
serde_json = { version = "1.0.142", optional = true }
bsdiff = { version = "0.2.1", optional = true }
once_cell = { version = "1.21.3", optional = true }
lazy_static = { version = "1.5.0", optional = true }
reqwest = { version = "0.12.23", default-features = false, features = ["rustls-tls", "blocking", "gzip", "http2", "rustls-tls-webpki-roots"], optional = true }
webpki-roots = { version = "1.0.2", optional = true }
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "io-util", "time"], optional = true }
reqwest-hickory-resolver = { version = "0.2.0", optional = true }
url = { version = "2.5.4", optional = true }
liblzma = { version = "0.4.2", features = ["static"] }


[features]
default = ["local_zip", "remote_ota", "metadata"]
remote_ota = ["dep:url", "dep:reqwest", "dep:webpki-roots", "dep:tokio", "dep:lazy_static"]
hickory-dns = ["remote_ota", "dep:once_cell", "dep:reqwest-hickory-resolver"]
differential_ota = ["dep:bsdiff"]
local_zip = []
metadata= ["dep:serde", "dep:serde_json"]


[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"
