[package]
name = "payload_dumper"
version = "0.7.4"
edition = "2024"
authors = ["rhythmcache"]
description = "A fast and efficient Android OTA payload dumper written in Rust"
repository = "https://github.com/rhythmcache/payload-dumper-rust"
readme = "README.md"
license = "Apache-2.0"
homepage = "https://github.com/rhythmcache/payload-dumper-rust"
keywords = ["dumper", "android", "ota", "extractor", "payload"]
categories = ["command-line-utilities"]

include = [
    "src/**",
    "LICENSE",
    "README.md",
    "Cargo.toml",
    "build.rs"
]

[[bin]]
name = "payload_dumper"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
byteorder = "1.5.0"
digest = "0.10.7"
indicatif = "0.18.0"
prost = "0.14.1"
sha2 = "0.10.9"
rayon = "1.11.0"
memmap2 = "0.9.8"
brotli = "8.0.2"
zstd = "0.13.3"
num_cpus = "1.17.0"
hex = "0.4.3"
bzip2 = { version = "0.6", features = ["bzip2-sys", "static"] }
clap = { version = "4.5.49", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"], optional = true }
serde_json = { version = "1.0.145", optional = true }
bsdiff = { version = "0.2.1", optional = true }
once_cell = { version = "1.21.3", optional = true }
lazy_static = { version = "1.5.0", optional = true }
reqwest = { version = "0.12.24", default-features = false, features = ["rustls-tls", "blocking", "gzip", "http2", "rustls-tls-webpki-roots"], optional = true }
webpki-roots = { version = "1.0.3", optional = true }
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "io-util", "time"], optional = true }
reqwest-hickory-resolver = { version = "0.2.0", optional = true }
url = { version = "2.5.7", optional = true }
liblzma = { version = "0.4.5", features = ["static"] }
lz4_flex = { version = "0.11.5", default-features = false, optional = true }

[build-dependencies]
chrono = "0.4.42"


[features]
default = ["local_zip", "remote_ota", "metadata"]
remote_ota = ["dep:url", "dep:reqwest", "dep:webpki-roots", "dep:tokio", "dep:lazy_static"]
hickory-dns = ["remote_ota", "dep:once_cell", "dep:reqwest-hickory-resolver"]
differential_ota = ["dep:bsdiff", "lz4_flex"]
local_zip = []
metadata = ["dep:serde", "dep:serde_json"]


[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"
