[package]
name = "payload_dumper"
version = "0.3.0"
edition = "2024"
authors = ["rhythmcache"]
description = "Rust-based CLI utility to extract Android OTA payload.bin"
repository = "https://github.com/rhythmcache/payload-dumper-rust"
readme = "README.md"
license = "Apache-2.0"
homepage = "https://github.com/rhythmcache/payload-dumper-rust"
keywords = ["dumper", "android", "ota" ,"extractor" ,"payload.bin"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "*"
byteorder = "*"
bzip2 = "*"
clap = { version = "*", features = ["derive"] }
digest = "*"
indicatif = "*"
rust-lzma = "*"
prost = "*"
sha2 = "*"
reqwest = { version = "*", default-features = false, features = ["rustls-tls", "blocking", "gzip", "http2"] }
webpki-roots = "*"
tokio = { version = "*", features = ["rt", "rt-multi-thread", "io-util", "time"] }
rayon = "*"
memmap2 = "*"
brotli = "*"
zstd = "*"
num_cpus = "*"
rand = "*"
hex = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
url = "*"
lazy_static = "*"
once_cell = "*"
reqwest-hickory-resolver = { version = "*", optional = true }


[features]
default = []
hickory-dns = ["reqwest-hickory-resolver"]



[build-dependencies]
prost-build = "*"
cc = "*"

[profile.release]
strip = true         
lto = true         
opt-level = "z"    
codegen-units = 1     
panic = "abort"    
