[package]
name = "payload_dumper"
version = "0.1.0"
edition = "2024"
description = "Android OTA Payload Dumper"
repository = "https://github.com/rhythmcache/payload-dumper-rust"

[dependencies]
anyhow = "1.0"
byteorder = "1.4"
bzip2 = "0.5"
clap = { version = "4.4", features = ["derive"] }
digest = "0.10"
indicatif = "0.17"
rust-lzma = "0.6.0"
prost = "0.12"
sha2 = "0.10"
attohttpc = { version = "0.29", default-features = false, features = ["rustls"] }
rayon = "1.8"
memmap2 = "0.9"
brotli = "3.4"
zstd = "0.13"
num_cpus = "1.16"
rand = "0.8"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.5"

[build-dependencies]
prost-build = "0.13"
cc = "1.0"

[profile.release]
strip = true         
lto = true         
opt-level = "z"    
codegen-units = 1     
panic = "abort"    
