name: Windows aarch64 mingw Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download LLVM-MinGW toolchain
        run: |
          cd /tmp
          wget https://github.com/mstorsjo/llvm-mingw/releases/download/20250812/llvm-mingw-20250812-msvcrt-ubuntu-22.04-x86_64.tar.xz
          tar -xf llvm-mingw-20250812-msvcrt-ubuntu-22.04-x86_64.tar.xz
          sudo mv llvm-mingw-20250812-msvcrt-ubuntu-22.04-x86_64 /opt/llvm-mingw
          echo "/opt/llvm-mingw/bin" >> $GITHUB_PATH

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Set target
        run: |
          echo "TARGET=aarch64-pc-windows-gnullvm" >> $GITHUB_ENV
          echo "ARCH_DIR=aarch64" >> $GITHUB_ENV
          echo "CC=aarch64-w64-mingw32-clang" >> $GITHUB_ENV
          echo "CXX=aarch64-w64-mingw32-clang++" >> $GITHUB_ENV
          echo "HOST_TRIPLE=aarch64-w64-mingw32" >> $GITHUB_ENV

      - name: Add Rust target
        run: rustup target add ${{ env.TARGET }}

      - name: Build for aarch64
        run: |
          echo "Building for ${{ env.TARGET }}"
          rm -f build.rs
          cargo build --release --target ${{ env.TARGET }} --features differential_ota
        env:
          PKG_CONFIG_ALLOW_CROSS: 1
          PKG_CONFIG_PATH: ${{ env.PKG_CONFIG_PATH }}

      - name: Create Dir
        run: mkdir -p artifacts

      - name: Copy binaries
        run: |
          cp target/${{ env.TARGET }}/release/payload_dumper.exe ./artifacts/payload_dumper-aarch64.exe || echo "Binary not found"
          if [ ! -f ./artifacts/payload_dumper-aarch64.exe ]; then
            echo "Failed to find binary"
            find target -type f -name "*.exe" | sort
          fi

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: payload_dumper-aarch64-windows
          path: artifacts/payload_dumper-aarch64.exe
          if-no-files-found: warn
